/**/bt_navigator:
  ros__parameters:
    #use_sim_time: True
    global_frame: map
    # robot_base_frame: base_link # set from launch file to add namespace
    odom_topic: odom
    bt_loop_duration: 10
    default_server_timeout: 20
   